spring:
    datasource:
        url: jdbc:mysql://localhost:3306/spring_boot_demo?useUnicode=true&characterEncoding=utf8
        username: carrx
        password: carrx@123
#        driver-class-name: com.mysql.jdbc.Driver

mybatis:
    typeAliasesPackage: org.spring.springboot.domain
    mapperLocations: classpath:mapper/*.xml